Cdl additions
loveland/schema pull request #20
Opened 2020-10-21 15:20 UTC by Blake-Loveland

2020-10-21 15:23 UTC, Blake-Loveland commented
Matt - Can you double check your memory for the cdl_majority_percent attribute. I know we agreed on the cdl_majority_category attribute, but I feel like it needs a a cdl_majority_percent no? What if it is 8.3% corn? 

I do not have that in my notes, but I feel like we talked about it last time we reviewed this, apologies for the last minute add here.

2020-10-21 17:30 UTC, hampelm commented
That is a good question on percent. You are the one working on this and I trust your judgement if it is important to include. I do not recall where we landed on `cdl_majority_percent`. I think we left it that people who needed the value should unpack it from `cdl_raw`? My instinctive reaction is always to use fewer columns, especially since we will need to maintain it and customers process it for year(s) to come. Either way this is good to go from me.

Oh one request -- could you add some example values in the schema? (search for `examples:` yml for example examples syntax) 

Related -- here's my last-minute peanut gallery addition ... don't kill me here but I figure this is the last chance to double check. Is there any value / sense in delivering this as a join table rather than in the parcel data, since it is only applying to one sector and segment of the country? Eg `ll_uuid,cdl_raw,cdl_majority_value,cdl_date`. I think I answered my own question which no, we can't use it easily on the platform as a join table.  I want to think about that sometime, how can we handle arbitrary add-ons without impacting the core schema... (having a system would also help with addresses). Ok sorry for the tangent.

2020-10-21 17:59 UTC, Blake-Loveland commented
I had the join table thought as well, and we might very well get the chance for that with the fedlands. When when i recalled why we were making the majority class items..... i put it back on the shelf for later.

And we had the the "pop the first one off the list" discussion as well... and you felt like the data would be a lot more accessible to you in our applications currently if it was not a nested something and you could just directly use the majority 'category label' and the 'percent' for that majority label.

I believe I just forgot that add that second item of the pair in to my notes, but we decided that instead of more work, i.e., pop it off, doing something, etc, we would just make the majority/plurality one its own attribute set.

indigo ag mentioned this as well, they were hoping we would make an easy to access 'majority' class type attribute, in addition to retaining the 'raw' data.

2020-10-21 18:01 UTC, hampelm commented
Definitely on the majority label, I am ambivalent on the majority value, I'm good whichever way that lands.

2020-10-22 10:28 UTC, Blake-Loveland commented
(I just do not see how one would feel comfortable using a crop category, e.g., Corn for anything unless you knew how much was corn, because it might be so little as to not be a meaningful label. I am not very imaginative though.)

cc @hampelm Examples added. Not sure about nesting the raw values in square brackets, or just the list of square bracketed pairs.

2020-10-29 13:51 UTC, hampelm requested changes
I just have small formatting requests that will help with display across platforms, and one small typo.

2020-10-29 13:51 UTC, hampelm commented on schema.yml
> +  human: Mailing Address State 2-Letter abbreviation
Could the "2-Letter abbreviation" part go in the `description:`? The reason I ask is because it's nice when these human-readable labels are as short as possible while maintaining legibility. That makes them easier to fit in a variety of sizes across different platforms (the same labels here are sent to the mobile apps, model builder, Filter form labels, etc)

2020-10-29 13:51 UTC, hampelm commented on schema.yml
> +  human: Mailing Address ISO 2-Letter County Code
Similar note as above about the ISO phrase possibly moving to `description:` for space (if that is still being included, I see Matthew's not in Slack that is often not an ISO code). 
County Code should gain an "r" to Country

2020-10-29 13:51 UTC, hampelm commented on schema.yml
> +    - [["36","60.0"],["75","20.0"],["87","10.0"],["190","10.0"]]
Examples look great

2020-10-29 13:51 UTC, hampelm commented on schema.yml
> +  human: All the Cropland Data Layer raw values
Could this be something like `Cropland Data Layer Raw Values`? 
I think raw implies all here, or that could go in description for conciseness? Using Title Case for the labels helps with consistency

2020-10-29 13:51 UTC, hampelm commented on schema.yml
> +  human: Date of the Cropland Data Layer data.
Could this be `Cropland Data Layer Data Date`? Or fine as is with `Data` caps and without period at the end for consistency

2020-10-29 20:47 UTC, hampelm approved these changes
Looks great to me

2020-11-12 15:30 UTC, merged