Adds q4 additions
loveland/schema pull request #36
Opened 2021-12-17 09:53 UTC by Blake-Loveland

2021-12-17 14:55 UTC, hampelm commented on schema.yml
> +  human: Census 2010 School District
2020 maybe? What is the latest we can get from Census?

2021-12-17 14:59 UTC, hampelm commented on schema.yml
> +secondary_address_count:
This one is tricky for me. 
I want that address count (secondary or ll_address_count) 
Are we putting _just_ secondary addresses -- aka addresses with a sunit -- in there or a total address count? Total address count would be a lot easier and have wider coverage

2021-12-17 15:58 UTC, lpuhl commented on schema.yml
> +  description: A county provided number in square feet that indicates the habitable area of buildings on the parcel.
1. So this is for residential square footage only? If so, I would change the `human` name to `Recorded Area of Residential Structures` for clarity. 
2. I would think it should be double precision rather than integer.

2021-12-17 16:02 UTC, lpuhl commented on schema.yml
> +  description: An assessor provided additional or alternative parcel identification number. If there is a state provided parcel identification number, it will be in this first alternative by conventi
So if there _isn't_ a state-provided PIN, but there is a secondary county PIN, that PIN will go in `alt_parcelnumb1`, right?

2022-01-05 06:59 UTC, Blake-Loveland commented on schema.yml
> +secondary_address_count:
total, let us call it 'total_address_count' instead of 'secondary_address_count', I will make that change.

2022-01-05 07:08 UTC, Blake-Loveland commented on schema.yml
> +  description: A county provided number in square feet that indicates the habitable area of buildings on the parcel.
This is for the square footage of the structure(s) on the parcel as provided by the county with no regard to residential or other designation. If you are seeing counties provide two or more structure area square footage attributes, please let me know and some indication of the number of counties providing more than one 'total square footage' type attribute.

If rare, I would suggest just totaling them and putting them in this field.

I think integer is fine, I would prefer to avoid the overhead of floats for square feet, most of which are integer values in my experience.

2022-01-05 07:11 UTC, Blake-Loveland commented on schema.yml
> +  description: An assessor provided additional or alternative parcel identification number. If there is a state provided parcel identification number, it will be in this first alternative by conventi
Yes, that is my thinking on this one. We also populate from 1 on up.

We did have a proposed field for 'state parcel id' type attribute, but thought this proposed solution might work ok.

I think it is still open for discussion if we need the dedicated attribute for state pid or not.

2022-01-05 07:29 UTC, Blake-Loveland commented on schema.yml
> +  human: Census 2010 School District
2021 is the latest for the shapes. Seems the shapes and attributes are updated yearly. I removed the year from the human readable label so we do not have to update this every year. I am not sure if we need to provide a date for these or not, but if we did, I would suggest the verse table would be the best place for it, it is not a critical date like last refresh, or the usps vacancy currency.

2022-01-05 07:35 UTC, Blake-Loveland commented on schema.yml
> +  description: A county provided number in square feet that indicates the habitable area of buildings on the parcel.
I also just updated both descriptions to hopefully make them more clear  and useful.

2022-01-05 19:16 UTC, hampelm requested changes
Have some new thoughts with fresh eyes

2022-01-05 19:16 UTC, hampelm commented on schema.yml
> +    - core
Should we do these with the `proposed` tag strategy as well? This is a genuine question; I am good rolling these out empty, but realized it might be cleaner for customers if they appeared with data in them, ready to go.

2022-01-05 19:16 UTC, hampelm commented on schema.yml
> +  description: The primary assessor's parcel identification number or code.
Maybe swap "primary" and "assessor's"? To read: 

> The assessor's primary parcel identification number or code.

2022-01-05 19:16 UTC, hampelm commented on schema.yml
> +  human: Parcel ID Unformatted
Bikeshedding: 
"Unformatted Parcel ID"? (adjective at the start)
"Parcel ID without Formatting"? (to match "no formatting")

2022-01-05 19:16 UTC, hampelm commented on schema.yml
> +  description: An assessor provided additional or alternative parcel identification number. If there is a state provided parcel identification number, it will be in this first alternative by conventi
cc @klovskim 

I don't have a strong feeling here. State parcel ID is definitely more explicit but if we have the convention that solves it 

How many states had statewide IDs? If it's a non-trivial % then it might make sense to keep the separate column

2022-01-05 19:16 UTC, hampelm commented on schema.yml
> +  description: An assessor provided additional or alternative parcel identification number.
Hyphenate assessor-provided?

2022-01-05 19:16 UTC, hampelm commented on schema.yml
> +  type: text
I think text is the way to go here, but I know some places do a % exemption, maybe worth a quick skim of some of the ~400+ counties that have a homestead column to make sure we're setting ourselves up well here.

2022-01-05 19:16 UTC, hampelm commented on schema.yml
> +    - census
Can we remove census_school_district from this rollout? I sent an email before break, but the short version is I believe it needs to be two columns. This one is a good candidate for the new `proposed` tag, which would let us set it up and populate the data, and test our assumptions, before rolling it out to customers.

2022-01-06 06:34 UTC, Blake-Loveland commented on schema.yml
> +    - core
I think cleaner for customers is going to be not having to mess with schema changes multiple times and just have the data populate with our data population process for those.

2022-01-06 15:17 UTC, hampelm commented on schema.yml
> +    - core
Works for me

2022-01-07 07:58 UTC, Blake-Loveland commented on schema.yml
> +  description: An assessor provided additional or alternative parcel identification number. If there is a state provided parcel identification number, it will be in this first alternative by conventi
I am leaning toward the separate column now, but still pretty impartial either way. 

The state pin attribute comes with it's own confusions, "is it an alternate parcel number and I should look in the alt fields, or is it a state pin and I should there?"

one may have no idea if it is a state pin or not, just that it is an alternate pin.

now I am back to only the alt pin number attributes, because if one did know it was a state pin, one would still reasonably classify it is also an alternate pin number, but not the other way around.

set theory here:
all state pins are alternate pins, but not all alternate pins are state pins.

so I am back to stick with the alternates only, and by convention if we have a state pin, it would alternate 1.

2022-01-07 08:02 UTC, Blake-Loveland commented on schema.yml
> +    - core
Sounds good, let us get them in there and prioritize populating them. thank you matt.

2022-01-07 08:08 UTC, Blake-Loveland commented on schema.yml
> +  human: Parcel ID Unformatted
I went with matt's suggested 'Parcel ID without Formatting' as I think that is more clear.

As 'unformatted' is kind of a format itself, and the 'without formatting' leads more toward, we removed formatting.

2022-01-07 08:10 UTC, Blake-Loveland commented on schema.yml
> +  description: An assessor provided additional or alternative parcel identification number.
sounds good to hyphenate, done.

2022-01-07 08:12 UTC, Blake-Loveland commented on schema.yml
> +  type: text
I think text still stays good here, i did not review current potential data, just going by memory, but even in the probably much fewer cases of a number, a text field lets us just put the % sign in there, and if it is a fractional number, text supports 0.123 mils etc.

2022-01-07 08:21 UTC, Blake-Loveland commented on schema.yml
> +    - census
I think just leaving it in the proposed state, but merged in, will be a tiny bit better than removing it totally.

2022-01-07 08:24 UTC, Blake-Loveland commented on schema.yml
> +  description: The primary assessor's parcel identification number or code.
done, good one.

2022-01-07 14:52 UTC, klovskim commented on schema.yml
> +  description: An assessor provided additional or alternative parcel identification number. If there is a state provided parcel identification number, it will be in this first alternative by conventi
I agree with blake on this one regarding state pin coming with its own confusions. I'm content just popping statepin (if there is one) going in alternate 1.

2022-01-12 14:06 UTC, merged